### ISSUE TITLE
Generate types from given json

### ISSUE THREAD

**Issue by agneym** [agneym/json-formatter#12]
1. Research type libraries for the same

**Comment by howareyouami** [comment]
Found some popular libraries

For multiple languages: https://github.com/quicktype/quicktype
For Type script: https://www.npmjs.com/package/json-schema-to-typescript

I will first try implementing one with only typeScript support, any suggestions?

**Comment by BoyWithSilverWings** [comment]
QuickType looks good to me. But as it stands, I would [build this feature as an extension] that people can use instead of adding it to the core. 

[Transform] is already added this way.

**Comment by howareyouami** [comment]
Then lets go with QuickType. Unlike Transform plugin, here the generated output can be shown inside the plugin itself with a `copy to clipboard` button. Is that enough?

**Comment by agneym** [comment]
Sure, that works :+1:
