### ISSUE TITLE
Ability to pin plugins/extensions 

### ISSUE THREAD

**Issue by agneym** [agneym/json-formatter#41]
**Is your feature request related to a problem? Please describe.**
Currently, the users have to go to the plugins tab to select the plugin they want to use each time they want to use it. 

**Describe the solution you'd like**
Should be able to pin an extension if they like one. It will appear as a tab alongside the plugins tab that currently exist. 

**Describe alternatives you've considered**
...

**Additional context**
This can be implmented by storing the selected plugin context into the local storage and then reading it from there when user reloads the page. Should also be able to unpin the extension. 

A challenge faced here would be incorportating this into the current UI. Suggestions welcome.

**Comment by howareyouami** [comment]
Some suggestions:

-  Show pin when hover list 
-  Limit the max no of plugins that can be pinned to 2 or 3 (stop showing hover pins)

![1](https://user-images.githubusercontent.com/26934320/71423033-d0070d00-269f-11ea-811f-2a5743f273b7.jpg)

-  Hide Plugins tab, Current plugin tab when open state

![2](https://user-images.githubusercontent.com/26934320/71423032-d0070d00-269f-11ea-9ea0-87fab2e0fd59.jpg)

-  If pinned, show unpin icon in both case

**Comment by agneym** [comment]
All of them sound to good to me :smile:

**Comment by howareyouami** [comment]
I am working on this
